---
abstract: 'authenticate people and read books!'
author:
  - 'Diego Kuperman <diego@freekeylabs.com>'
build_requires:
  Catalyst: 0
  Catalyst::Controller: 0
  Catalyst::Runtime: 5.80
  FindBin: 0
  Moose: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-TraitFor-Controller-reCAPTCHA
requires:
  Captcha::reCAPTCHA: 0
  Carp: 0
  Moose::Role: 0
  MooseX::MethodAttributes::Role: 0
  namespace::autoclean: 0
version: 1.112812
